--- 

- hosts: all
  become: True
  tasks:
    - name: Atualiza o cache do apt
      apt: 
        update_cache: yes
      tags:
        - packages
    
    - name: Instala o nginx
      apt:
        name: nginx
        state: present
      tags:
        - packages
    
    - name: Criando diretorio para os arquivos do j2 e html
      file:
        path: /var/www/site1
        state: directory
        mode: '0755'
        
    
    - name: Criando diretorio para os arquivos do
      file:
        path: /var/www/site2
        state: directory
        mode: '0755'
   
    - name: Copia a pagina web para o diretorio do nginx
      copy: 
        src: files/
        dest: /var/www/site1
        owner: www-data
        group: www-data
        mode: '0644'
      notify:
        - Reiniciar nginx
    


    - name: Copia a pagina web para um dos diretorios do nginx
      copy:
        src: files/
        dest: /var/www/site2/
        owner: www-data
        group: www-data
        mode: '0644'
      
      
    - name: Template
      template:
        src: index.html.j2
        dest: /var/www/site2/index.html
        mode: '0644'
      vars:
        site_informacao: "Testando1 2 3"
      notify:
        - Reiniciar nginx

    - name: Criando os arquivos do nginx
      copy:
        src: nginx-files/
        dest: /etc/nginx/sites-available
        owner: root
        group: root
        mode: '0600'
    
    - name: Criando SL para o site1
      file:
        src: /etc/nginx/sites-available/site1.conf
        dest: /etc/nginx/sites-enabled/site1.conf
        owner: root
        group: root
        state: link
    
    - name: Criando SL para o site2
      file:
        src: /etc/nginx/sites-available/site2.conf
        dest: /etc/nginx/sites-enabled/site2.conf
        owner: root
        group: root
        state: link
    
  handlers:
    - name: Reiniciar nginx
      service:
        name: nginx
        state: restarted
    
